<template>
  <div class="bg-white">
    <div class="mx-auto max-w-7xl px-6 py-24 sm:pt-32 lg:px-8 lg:py-40">
      <div class="lg:grid lg:grid-cols-12 lg:gap-8">
        <div class="lg:col-span-5">
          <h2 class="text-2xl font-bold leading-10 tracking-tight text-gray-900">Frequently asked questions</h2>
          <p class="mt-4 text-base leading-7 text-gray-600">
            Can’t find the answer you’re looking for? Reach out to our<!-- -->
            <a href="#" class="font-semibold text-indigo-600 hover:text-indigo-500">customer support</a>
            <!-- -->team.
          </p>
        </div>
        <div class="mt-10 lg:col-span-7 lg:mt-0">
          <dl class="space-y-10">
            <div>
              <dt class="text-base font-semibold leading-7 text-gray-900">How does BuzLink work?</dt>
              <dd class="mt-2 text-base leading-7 text-gray-600">BuzLink is a URL shortening service that takes long
                URLs and converts them into shorter, more manageable links. Users can simply paste their long URL into
                the BuzLink website and receive a shortened link to share.</dd>
            </div>
            <div>
              <dt class="text-base font-semibold leading-7 text-gray-900">Is BuzLink free to use?</dt>
              <dd class="mt-2 text-base leading-7 text-gray-600">Yes, BuzLink is completely free to use. There are no
                hidden fees or charges for shortening URLs on our platform.</dd>
            </div>
            <div>
              <dt class="text-base font-semibold leading-7 text-gray-900">Can I customize the shortened URLs on BuzLink?
              </dt>
              <dd class="mt-2 text-base leading-7 text-gray-600">Yes, BuzLink offers the option to customize shortened
                URLs with a unique alias. Users can choose a custom alias for their shortened link to make it more
                personalized.</dd>
            </div>
            <div>
              <dt class="text-base font-semibold leading-7 text-gray-900">How long are the shortened URLs on BuzLink?
              </dt>
              <dd class="mt-2 text-base leading-7 text-gray-600">The shortened URLs generated by BuzLink are typically
                around 10-15 characters long. This makes them easy to share and remember.</dd>
            </div>
            <div>
              <dt class="text-base font-semibold leading-7 text-gray-900">Is there a limit to how many URLs I can
                shorten on BuzLink?</dt>
              <dd class="mt-2 text-base leading-7 text-gray-600">No, there is no limit to the number of URLs you can
                shorten on BuzLink. Users can shorten as many URLs as they need without any restrictions.</dd>
            </div>
          </dl>
        </div>
      </div>
    </div>
  </div>
</template>